known_extensions = {
    'images': ('.jpeg', '.png', '.jpg', '.svg', '.gif', '.bmp', '.tiff'),
    'video': ('.avi', '.mp4', '.mov', '.mkv', '.wmv', '.flv', '.webm'),
    'audio': ('.mp3', '.ogg', '.wav', '.amr', '.flac', '.aac', '.m4a'),
    'documents': ('.doc', '.docx', '.txt', '.pdf', '.xlsx', '.pptx', '.odt', '.rtf', '.tex'),
    'archives': ('.zip', '.gz', '.tar', '.rar', '.7z', '.bz2'),
    'code': ('.py', '.java', '.cpp', '.html', '.css', '.js', '.php'),
    'spreadsheets': ('.csv', '.xls', '.xlsx', '.ods'),
    'presentations': ('.ppt', '.pptx', '.key'),
    'executables': ('.exe', '.dll', '.msi', '.bat', '.sh'),
    'fonts': ('.ttf', '.otf', '.woff', '.eot'),
    'databases': ('.sqlite', '.db', '.sql', '.json'),
    'webpages': ('.html', '.htm', '.php', '.asp'),
    'scripts': ('.bat', '.sh', '.ps1', '.bash', '.cmd'),
    'backup': ('.bak', '.backup', '.old'),
    'config': ('.conf', '.ini', '.cfg', '.yaml'),
    'json': ('.json',),
    'xml': ('.xml',),
    'log': ('.log', '.txt'),
    'torrents': ('.torrent',),
    'virtual_machines': ('.vdi', '.vmware', '.vbox', '.ova'),
    'images_raw': ('.raw',),
    'audio_raw': ('.raw',),
    'videos_raw': ('.raw',),
    '3d_models': ('.obj', '.stl', '.blend', '.fbx'),
    'ebooks': ('.epub', '.mobi', '.azw', '.pdf'),
    'gis_files': ('.shp', '.kml', '.kmz', '.gpx'),
    'data_files': ('.csv', '.tsv', '.json', '.xml', '.yaml'),
    'web_files': ('.html', '.css', '.js', '.php'),
    'configs': ('.conf', '.ini', '.cfg', '.yaml'),
    'compressed_images': ('.jpeg', '.png', '.jpg'),
    'other': ('.bin', '.dat', '.tmp', '.temp'),
}